"""
Protocol enumerations for Graal Reborn
"""

from enum import IntEnum

class PlayerToServer(IntEnum):
    """Client to server packet types"""
    PLI_LEVELWARP = 0
    PLI_BOARDMODIFY = 1
    PLI_PLAYERPROPS = 2
    PLI_NPCPROPS = 3
    PLI_BOMBADD = 4
    PLI_BOMBDEL = 5
    PLI_TOALL = 6
    PLI_HORSEADD = 7
    PLI_HORSEDEL = 8
    PLI_ARROWADD = 9
    PLI_FIRESPY = 10
    PLI_THROWCARRIED = 11
    PLI_ITEMADD = 12
    PLI_ITEMDEL = 13
    PLI_CLAIMPKER = 14
    PLI_BADDYPROPS = 15
    PLI_BADDYHURT = 16
    PLI_BADDYADD = 17
    PLI_FLAGSET = 18
    PLI_FLAGDEL = 19
    PLI_OPENCHEST = 20
    PLI_PUTNPC = 21
    PLI_NPCDEL = 22
    PLI_WANTFILE = 23
    PLI_SHOWIMG = 24
    PLI_UNKNOWN25 = 25
    PLI_HURTPLAYER = 26
    PLI_EXPLOSION = 27
    PLI_PRIVATEMESSAGE = 28
    PLI_NPCWEAPONDEL = 29
    PLI_LEVELWARPMOD = 30
    PLI_PACKETCOUNT = 31
    PLI_ITEMTAKE = 32
    PLI_WEAPONADD = 33
    PLI_UPDATEFILE = 34
    PLI_ADJACENTLEVEL = 35
    PLI_HITOBJECTS = 36
    PLI_LANGUAGE = 37
    PLI_TRIGGERACTION = 38
    PLI_MAPINFO = 39
    PLI_SHOOT = 40
    PLI_SERVERWARP = 41
    PLI_MUTEPLAYER = 43
    PLI_PROCESSLIST = 44
    PLI_UNKNOWN46 = 46
    PLI_VERIFYWANTSEND = 47
    PLI_SHOOT2 = 48
    PLI_RAWDATA = 50
    PLI_RC_LISTRCS = 65

class ServerToPlayer(IntEnum):
    """Server to client packet types"""
    PLO_LEVELBOARD = 0
    PLO_LEVELLINK = 1
    PLO_BADDYPROPS = 2
    PLO_NPCPROPS = 3
    PLO_LEVELCHEST = 4
    PLO_LEVELSIGN = 5
    PLO_LEVELNAME = 6
    PLO_BOARDMODIFY = 7
    PLO_OTHERPLPROPS = 8
    PLO_PLAYERPROPS = 9
    PLO_ISLEADER = 10
    PLO_BOMBADD = 11
    PLO_BOMBDEL = 12
    PLO_TOALL = 13
    PLO_PLAYERWARP = 14
    PLO_WARPFAILED = 15
    PLO_DISCMESSAGE = 16
    PLO_HORSEADD = 17
    PLO_HORSEDEL = 18
    PLO_ARROWADD = 19
    PLO_FIRESPY = 20
    PLO_THROWCARRIED = 21
    PLO_ITEMADD = 22
    PLO_ITEMDEL = 23
    PLO_NPCMOVED = 24
    PLO_SIGNATURE = 25
    PLO_NPCACTION = 26
    PLO_BADDYHURT = 27
    PLO_FLAGSET = 28
    PLO_NPCDEL = 29
    PLO_FILESENDFAILED = 30
    PLO_FLAGDEL = 31
    PLO_SHOWIMG = 32
    PLO_NPCWEAPONADD = 33
    PLO_NPCWEAPONDEL = 34
    PLO_RC_ADMINMESSAGE = 35
    PLO_EXPLOSION = 36
    PLO_PRIVATEMESSAGE = 37
    PLO_PUSHAWAY = 38
    PLO_LEVELMODTIME = 39
    PLO_HURTPLAYER = 40
    PLO_STARTMESSAGE = 41
    PLO_NEWWORLDTIME = 42
    PLO_DEFAULTWEAPON = 43
    PLO_HASNPCSERVER = 44
    PLO_FILEUPTODATE = 45
    PLO_HITOBJECTS = 46
    PLO_STAFFGUILDS = 47
    PLO_TRIGGERACTION = 48
    PLO_PLAYERWARP2 = 49
    PLO_ADDPLAYER = 55
    PLO_DELPLAYER = 56
    PLO_LARGEFILESTART = 68
    PLO_LARGEFILEEND = 69
    PLO_RC_CHAT = 74
    PLO_PROFILE = 75
    PLO_NPCSERVERADDR = 79
    PLO_SERVERTEXT = 82
    PLO_LARGEFILESIZE = 84
    PLO_RAWDATA = 100
    PLO_BOARDPACKET = 101
    PLO_FILE = 102
    PLO_UPDATEPACKAGESIZE = 105
    PLO_UPDATEPACKAGEDONE = 106
    PLO_BOARDLAYER = 107
    PLO_NPCBYTECODE = 131
    PLO_GANISCRIPT = 134
    PLO_NPCWEAPONSCRIPT = 140
    PLO_NPCDEL2 = 150
    PLO_HIDENPCS = 151
    PLO_SAY2 = 153
    PLO_FREEZEPLAYER2 = 154
    PLO_UNFREEZEPLAYER = 155
    PLO_SETACTIVELEVEL = 156
    PLO_RPGWINDOW = 179
    PLO_STATUSLIST = 180
    PLO_LISTPROCESSES = 182
    PLO_MOVE2 = 189
    PLO_SHOOT2 = 191
    PLO_CLEARWEAPONS = 194
    PLO_UNKNOWN197 = 197
    PLO_UNKNOWN198 = 198
    PLO_NC_CLASSADD = 163
    PLO_FULLSTOP2 = 177

class PlayerProp(IntEnum):
    """Player property types"""
    PLPROP_NICKNAME = 0
    PLPROP_MAXPOWER = 1
    PLPROP_CURPOWER = 2
    PLPROP_RUPEESCOUNT = 3
    PLPROP_ARROWSCOUNT = 4
    PLPROP_BOMBSCOUNT = 5
    PLPROP_GLOVEPOWER = 6
    PLPROP_BOMBPOWER = 7
    PLPROP_SWORDPOWER = 8
    PLPROP_SHIELDPOWER = 9
    PLPROP_GANI = 10
    PLPROP_HEADGIF = 11
    PLPROP_CURCHAT = 12
    PLPROP_COLORS = 13
    PLPROP_ID = 14
    PLPROP_X = 15
    PLPROP_Y = 16
    PLPROP_SPRITE = 17
    PLPROP_STATUS = 18
    PLPROP_CARRYSPRITE = 19
    PLPROP_CURLEVEL = 20
    PLPROP_HORSEGIF = 21
    PLPROP_HORSEBUSHES = 22
    PLPROP_EFFECTCOLORS = 23
    PLPROP_CARRYNPC = 24
    PLPROP_APCOUNTER = 25
    PLPROP_MAGICPOINTS = 26
    PLPROP_KILLSCOUNT = 27
    PLPROP_DEATHSCOUNT = 28
    PLPROP_ONLINESECS = 29
    PLPROP_IPADDR = 30
    PLPROP_UDPPORT = 31
    PLPROP_ALIGNMENT = 32
    PLPROP_ADDITFLAGS = 33
    PLPROP_ACCOUNTNAME = 34
    PLPROP_BODYIMG = 35
    PLPROP_RATING = 36
    PLPROP_GATTRIB1 = 37
    PLPROP_GATTRIB2 = 38
    PLPROP_GATTRIB3 = 39
    PLPROP_GATTRIB4 = 40
    PLPROP_GATTRIB5 = 41
    PLPROP_PLATTRIB1 = 42
    PLPROP_PLATTRIB2 = 43
    PLPROP_PLATTRIB3 = 44
    PLPROP_PLATTRIB4 = 45
    PLPROP_PLATTRIB5 = 46
    PLPROP_PLSELCHAT = 47
    PLPROP_PLGUILDMOD = 48
    
    # Extended properties
    PLPROP_Z = 45  # Z coordinate (old style)
    # ... (46-77 are various GATTRIB and other properties)
    PLPROP_X2 = 78  # High precision X (v2.30+)
    PLPROP_Y2 = 79  # High precision Y (v2.30+)
    PLPROP_Z2 = 80  # High precision Z (v2.30+)
    PLPROP_UNKNOWN81 = 81
    PLPROP_COMMUNITYNAME = 82
    PLPROP_PLPOSSESSITEM = 49
    PLPROP_PLSTATUS = 50
    PLPROP_GATTRIB6 = 51
    PLPROP_GATTRIB7 = 52
    PLPROP_GATTRIB8 = 53
    PLPROP_GATTRIB9 = 54
    PLPROP_GATTRIB10 = 55
    PLPROP_GATTRIB11 = 56
    PLPROP_GATTRIB12 = 57
    PLPROP_GATTRIB13 = 58
    PLPROP_GATTRIB14 = 59
    PLPROP_GATTRIB15 = 60
    PLPROP_GATTRIB16 = 61
    PLPROP_GATTRIB17 = 62
    PLPROP_GATTRIB18 = 63
    PLPROP_GATTRIB19 = 64
    PLPROP_GATTRIB20 = 65
    PLPROP_GATTRIB21 = 66
    PLPROP_GATTRIB22 = 67
    PLPROP_GATTRIB23 = 68
    PLPROP_GATTRIB24 = 69
    PLPROP_GATTRIB25 = 70
    PLPROP_GATTRIB26 = 71
    PLPROP_GATTRIB27 = 72
    PLPROP_GATTRIB28 = 73
    PLPROP_GATTRIB29 = 74
    PLPROP_GATTRIB30 = 75
    PLPROP_UNKNOWN77 = 77

class PlayerStatus(IntEnum):
    """Player status flags"""
    PLSTATUS_PAUSED = 0x01
    PLSTATUS_HIDDEN = 0x02
    PLSTATUS_MALE = 0x04
    PLSTATUS_DEAD = 0x08
    PLSTATUS_ALLOWWEAPONS = 0x10
    PLSTATUS_HIDESWORD = 0x20
    PLSTATUS_HASSPIN = 0x40

class PlayerType(IntEnum):
    """Player/connection types"""
    PLTYPE_AWAIT = -1
    PLTYPE_CLIENT = 1 << 0
    PLTYPE_RC = 1 << 1
    PLTYPE_NPCSERVER = 1 << 2
    PLTYPE_NC = 1 << 3
    PLTYPE_CLIENT2 = 1 << 4
    PLTYPE_CLIENT3 = 1 << 5
    PLTYPE_RC2 = 1 << 6
    PLTYPE_EXTERNAL = 1 << 7
    PLTYPE_WEB = 1 << 8

class ClientVersion(IntEnum):
    """Client version identifiers"""
    VERSION_1X = 0
    VERSION_20 = 1
    VERSION_21 = 2
    VERSION_22 = 3
    VERSION_3X = 4

class LevelItemType(IntEnum):
    """Level item types"""
    GREENRUPEE = 0
    BLUERUPEE = 1
    REDRUPEE = 2
    BOMBS = 3
    DARTS = 4
    HEART = 5
    GLOVE1 = 6
    BOW = 7
    BOMB = 8
    SHIELD = 9
    SWORD = 10
    FULLHEART = 11
    SUPERBOMB = 12
    BATTLEAXE = 13
    GOLDENSWORD = 14
    MIRRORSHIELD = 15
    GLOVE2 = 16
    LIZARDSHIELD = 17
    LIZARDSWORD = 18
    GOLDRUPEE = 19
    FIREBALL = 20
    FIREBLAST = 21
    NUKESHOT = 22
    JOLTBOMB = 23

class Direction(IntEnum):
    """Player direction/facing"""
    UP = 0
    LEFT = 1
    DOWN = 2
    RIGHT = 3