window:
  width: 1600
  height: 900
  title: Reborn Modern
  fps: 60

client:
  host: localhost
  port: 14900
  version: 6.037

debug:
  show_fps: true
  packet_inspector: false
  coordinate_overlay: false

audio:
  enabled: true
  master_volume: 0.7
  music_volume: 0.5
  sfx_volume: 0.8

graphics:
  vsync: true
  smooth_scaling: true
  tile_size: 16

keybindings:
  move_up: up
  move_down: down
  move_left: left
  move_right: right
  attack: space
  grab: ctrl
  chat: enter
  toggle_debug: f3
  toggle_coords: f4
  toggle_fullscreen: f11