# MkDocs configuration for OpenGraal2 documentation
# This configuration creates a ReadTheDocs-style documentation site

site_name: OpenGraal2 Documentation
site_description: Modern Python implementation of Graal Reborn client and server
site_author: OpenGraal2 Contributors
site_url: https://opengraal2.readthedocs.io

# Repository information
repo_name: opengraal2/opengraal2
repo_url: https://github.com/user/opengraal2
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
    - json

# Navigation structure
nav:
  - Home: index.md
  
  - PyReborn Library:
    - API Reference: pyreborn/api-reference.md
    - Architecture Guide: pyreborn/architecture.md
    - Protocol Implementation: pyreborn/protocol.md
    - Event System: pyreborn/events.md
    - Bot Development: pyreborn/bot-development.md
    - Extending PyReborn: pyreborn/extending.md
    - Examples: pyreborn/examples.md
    
  - Classic Reborn Client:
    - Overview: classic-client/overview.md
    - Development Guide: classic-client/development.md
    - GMAP Support: classic-client/gmap.md
    - Graphics System: classic-client/graphics.md
    - Audio System: classic-client/audio.md
    - Controls & Input: classic-client/controls.md
    
  - Server Setup:
    - Docker Server: server/docker-setup.md
    - Configuration: server/configuration.md
    - Level Creation: server/level-creation.md
    - Admin Guide: server/admin-guide.md
    
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Debugging: development/debugging.md
    - Performance: development/performance.md
    - Refactoring Recommendations: refactoring-recommendations.md
    
  - Tutorials:
    - Quick Start: tutorials/quick-start.md
    - Your First Bot: tutorials/first-bot.md
    - Custom Client: tutorials/custom-client.md
    - Server Hosting: tutorials/server-hosting.md
    
  - Reference:
    - Graal Protocol: reference/protocol-spec.md
    - GANI Format: reference/gani-format.md
    - Tileset Format: reference/tileset-format.md
    - Level Format: reference/level-format.md

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugin configuration
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true

# Custom CSS
extra_css:
  - css/custom.css

# Extra JavaScript
extra_javascript:
  - js/custom.js

# Additional configuration
extra:
  version: 1.0.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/user/opengraal2
    - icon: fontawesome/brands/discord
      link: https://discord.gg/opengraal2

# Copyright
copyright: Copyright &copy; 2024 OpenGraal2 Contributors

# Build settings
docs_dir: '.'
site_dir: '../docs-build'

# Validation settings
strict: false
use_directory_urls: true